# Makefile 
# 
# Objetivo: Exibir uma mensagem de Olá mundo na tela.
# 
# Versão 1.0
# 
# Site: http://www.dirackslounge.online
# 
# Programador: Rodolfo A. C. Neves (Dirack) 09/06/2019
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: Software de uso livre e código aberto.


all:
	echo "Olá mundo, Makefile! :)"
