# Makefile 
# 
# Objetivo: Exemplo compilação simples de arquivos com Makefile.
# 
# Versão 1.0
# 
# Site: http://www.dirackslounge.online
# 
# Programador: Rodolfo A. C. Neves (Dirack) 09/06/2019
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: Software de uso livre e código aberto.

# Exemplo Makefile compilação simples

all:	teste.x run

teste.x:	teste.f90
	gfortran teste.f90 -o teste.x

run:	teste.x
	./teste.x
