# Makefile 
# 
# Objetivo: Exemplo passo a passo da lógica dos arquivos Makefile.
#
#	'make' executa os comandos do alvo 'all'
#	'make mensagem2' executa apenas o alvo 'mensagem2'
#	'make criardiretorio' cria um diretorio na pasta atual
# 
# Versão 1.0
# 
# Site: http://www.dirackslounge.online
# 
# Programador: Rodolfo A. C. Neves (Dirack) 14/06/2019
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: Software de uso livre e código aberto.

all:	mensagem1 mensagem2
	@echo "Olá mundo Makefile!"

mensagem1:
	@echo "Oi eu sou a mensagem 1"

mensagem2:
	@echo "Sou a mensagem 2"

criardiretorio:
	@mkdir diretorio1
